# Site settings
title: Ash Coolman's docs
email: writetofish at gmail
description: > # this means to ignore newlines until "baseurl:"
  My documentation on web technologies
highlighter: kramdown
github: git@github.com:AshCoolman/docs.git
baseurl: "/docs" # the subpath of your site, e.g. /blog/
url: "http://ashcoolman.com" # the base hostname & protocol for your site
twitter_username: Ash_Coolman
github_username:  AshCoolman

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge