# Site settings
title: Ashcoolman's docs
email: ashley@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my docs site
highlighter: pygments
github: git@github.com:AshCoolman/docs.git
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ashcoolman.com" # the base hostname & protocol for your site
twitter_username: ashcoolman
github_username:  AshCoolman

# Build settings
markdown: kramdown

# Sass settings
sass:
    sass_dir: _sass
    style: :compressed
